# Generated by Django 2.2.4 on 2020-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
    ]
