// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdCat.Models;

namespace ProdCat.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200816040058_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProdCat.Models.Associations", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("getCategoryCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("getProductProductId")
                        .HasColumnType("int");

                    b.HasKey("AssociationId");

                    b.HasIndex("getCategoryCategoryId");

                    b.HasIndex("getProductProductId");

                    b.ToTable("TheAssociations");
                });

            modelBuilder.Entity("ProdCat.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("TheCategories");
                });

            modelBuilder.Entity("ProdCat.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.ToTable("TheProducts");
                });

            modelBuilder.Entity("ProdCat.Models.Associations", b =>
                {
                    b.HasOne("ProdCat.Models.Categories", "getCategory")
                        .WithMany("myAssociation")
                        .HasForeignKey("getCategoryCategoryId");

                    b.HasOne("ProdCat.Models.Products", "getProduct")
                        .WithMany("myAssociation")
                        .HasForeignKey("getProductProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
