# Generated by Django 2.2.4 on 2020-06-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20200617_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='users',
            new_name='user',
        ),
    ]
