# Generated by Django 2.2.4 on 2020-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='book_reviewed',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_reviewed',
            new_name='user',
        ),
    ]
